<a href="https://colab.research.google.com/github/pepek1910/LearnKeras/blob/master/NNFromCSVFECTEtap2_keras_DNN_khanrad_tut_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
tutorial keras z YB - https://www.youtube.com/watch?v=zinEPDj7SD8

In [2]:
import keras
import numpy as np
import pandas as pd

!pip install ipython-autotime

In [3]:
train_data = pd.read_csv('/content/drive/MyDrive/NeuralNetwork/Dokt/Etap2/EtapV2Train.csv')
test_data = pd.read_csv('/content/drive/MyDrive/NeuralNetwork/Dokt/Etap2/Etap2V2Test.csv')
#df.head()

In [4]:
X = train_data.drop(columns=['Output'])
Y = train_data[['Output']]
X1 = test_data.drop(columns=['Output'])
Y1 = test_data[['Output']]

In [5]:
model = keras.Sequential()
model.add(keras.layers.Dense(16, activation='relu', input_shape=(100,))) #take all values and normilze it from 0 to 1, if its close to 1 its 1 if it close to 0 its 0 (or others sigmoid..)
model.add(keras.layers.Dense(32, activation='relu'))
model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dropout(0.1))
model.add(keras.layers.Dense(4))
# model.add(keras.layers.Dense(1))

model.compile(optimizer='adam',  loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),metrics=['accuracy'])
#model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])#(loss = 'categorical_crossentropy', optimizer='adam', metrics=['accuracy']) #optimizer='rmsprop'
%load_ext autotime


time: 154 µs (started: 2021-12-04 11:34:08 +00:00)


In [ ]:
#test struktury sieci neuronowej
# model = keras.Sequential()
# model.add(keras.layers.Dense(100,  activation='relu',input_shape=(100,)))
# model.add(keras.layers.Dense(100, activation='relu'))
# model.add(keras.layers.Dense(1, activation='sigmoid'))

# model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# model.fit(X, Y, epochs=150, batch_size=10)

In [6]:
history = model.fit(X,Y, epochs=130, steps_per_epoch=200, validation_data = (X1,Y1))#, verbose = 1, validation_steps=3)
#history = model.fit(X,Y, epochs=130,steps_per_epoch=200)
accuracy = model.evaluate(X, Y)
# print('Accuracy: %.2f' % (accuracy*100))
%load_ext autotime

 #callbacks=[keras.callbacks.EarlyStopping(patience=5)]) #to stop overfitting set callbacks, when it will not getting much better it will stop eaven if thera are some epoch left

Epoch 1/130
200/200 [==============================] - 1s 4ms/step - loss: 0.7997 - accuracy: 0.7470 - val_loss: 0.7243 - val_accuracy: 0.5875
Epoch 2/130
200/200 [==============================] - 0s 2ms/step - loss: 0.3113 - accuracy: 0.8965 - val_loss: 0.3047 - val_accuracy: 0.8900
Epoch 3/130
200/200 [==============================] - 0s 2ms/step - loss: 0.2036 - accuracy: 0.9415 - val_loss: 0.2369 - val_accuracy: 0.9325
Epoch 4/130
200/200 [==============================] - 0s 2ms/step - loss: 0.1409 - accuracy: 0.9525 - val_loss: 0.1642 - val_accuracy: 0.9425
Epoch 5/130
200/200 [==============================] - 0s 2ms/step - loss: 0.0940 - accuracy: 0.9680 - val_loss: 0.1608 - val_accuracy: 0.9500
Epoch 6/130
200/200 [==============================] - 0s 2ms/step - loss: 0.0777 - accuracy: 0.9730 - val_loss: 0.1019 - val_accuracy: 0.9725
Epoch 7/130
200/200 [==============================] - 0s 2ms/step - loss: 0.0671 - accuracy: 0.9750 - val_loss: 0.1333 - val_accuracy: 0.9450

In [23]:
import tensorflow as tf
import pandas as pd
External_data=pd.read_csv('/content/drive/MyDrive/NeuralNetwork/Dokt/Etap2/TestExternalNoHeaderPo100.csv', sep=',',header=None)

first_data_of_adjustable = 0
last_data_of_adjustable = 99
first_data_of_shape = 100
last_data_of_shape = 199
first_data_of_traingle = 200
last_data_of_traingle = 299
first_data_of_wrench = 300
last_data_of_wrench = 399
wrong_adjustable = 0
wrong_shape = 0
wrong_traingle = 0
wrong_wrench = 0
wrong_adjustable_table = []
wrong_shape_table = []
wrong_traingle_table = []
wrong_wrench_table = []
wrong_adjustable_table_sample = []
wrong_shape_table_sample = []
wrong_traingle_table_sample = []
wrong_wrench_table_sample = []
good_adjustable = 0
good_shape = 0
good_traingle = 0
good_wrench = 0
adjustable_number = 0
shape_number = 0
triangle_number = 0
wrench_number = 0
test_number = 0
sum_all = 0
prediction =0
classified_wrench_except_adjustable = 0
classified_adjustable_except_wrench = 0

print("Test danych zewnętrznych. Jest po 100 danych z każdej klasy")
print("Klasyfikacja obiektów {'adjustable': 0, 'shape': 1, 'triangle': 2, 'wrench': 3}")
for th in range(400):
  path = th
  print(th) 
  data =External_data.values[path]
  classes = model.predict(data.reshape(1,100), batch_size=1)
  score = tf.nn.softmax(classes[0])
  prediction =score
  print(prediction)
  pred = np.argmax(classes)
  print(pred)
  prediction =classes[0]
  print(prediction)

  if (th>=first_data_of_adjustable and th<=last_data_of_adjustable): # 99 bo zaczyna od 0
    adjustable_number = adjustable_number+1
    if pred == 0:
      good_adjustable = good_adjustable+1
    # elif pred ==3:
    #   classified_wrench_except_adjustable = classified_wrench_except_adjustable + 1   
    else:
      wrong_adjustable_table_sample.append(th)
      wrong_adjustable_table.append(prediction)
      wrong_adjustable=wrong_adjustable+1
  elif (th>=first_data_of_shape and th<=last_data_of_shape):
    shape_number = shape_number +1
    if pred ==1:
      good_shape = good_shape+1
    else:
      wrong_shape_table_sample.append(th)
      wrong_shape_table.append(prediction)
      wrong_shape=wrong_shape+1    
  elif (th>=first_data_of_traingle and th<=last_data_of_traingle):
    triangle_number = triangle_number+ 1
    if pred ==2:
      good_traingle= good_traingle+1
    else:
      wrong_traingle_table_sample.append(th)
      wrong_traingle_table.append(prediction)
      wrong_traingle=wrong_traingle+1  
  elif (th>=first_data_of_wrench and th<=last_data_of_wrench):
    wrench_number = wrench_number +1
    if pred ==3:
      good_wrench = good_wrench+1
    # elif pred ==0:
    #   classified_adjustable_except_wrench = classified_adjustable_except_wrench + 1  
    else:
      wrong_wrench_table_sample.append(th)
      wrong_wrench_table.append(prediction)
      wrong_wrench=wrong_wrench+1


# #wyswietlenie wynikow 
sum_all = good_adjustable+wrong_adjustable+good_shape+wrong_shape+good_traingle+wrong_traingle+good_wrench+wrong_wrench
  #print(round(classes,12))
  #print(round(float(classes))) - zaokraglenie powoduje przyporzadkowanie do klasy
print("--------Well Classified-------------------") 
print("----Adjustable----")
print("good adjustable = "+str(good_adjustable))
print("Wrong adjustable = "+str(wrong_adjustable))
print("Wrong adjustable test ")
print(wrong_adjustable_table_sample)
print(wrong_adjustable_table)
print("----Shape----")
print("good shape = "+str(good_shape))
print("Wrong shape = "+str(wrong_shape)) 
print("Wrong shape test:")
print(wrong_shape_table_sample)
print(wrong_shape_table)
print("----Triangle----")
print("good triangle = "+str(good_traingle)) 
print("Wrong triangle = "+str(wrong_traingle))
print("Wrong triangle test")
print(wrong_traingle_table_sample)
print(wrong_traingle_table)
print("----Wrench----")
print("good wrench = "+str(good_wrench))       
print("Wrong wrench = "+str(wrong_wrench))
print("Wrong wrench test:")
print(wrong_wrench_table_sample)
print(wrong_wrench_table)
print("----Sum Up----")
print("All Tests ="+str(sum_all))
%load_ext autotime

  #dobra udalo sie trzeba podpiac alorytm sprawdzania z etapu 1 i gitara( bo wyswietla juz nie tylko wartosci na ywjsciu, ale tez prwdopodpobienstwa i przyporzadkowanie do klasy :)

Test danych zewnętrznych. Jest po 100 danych z każdej klasy
Klasyfikacja obiektów {'adjustable': 0, 'shape': 1, 'triangle': 2, 'wrench': 3}
0
tf.Tensor([9.9999928e-01 4.6919482e-08 5.0840701e-17 6.6350105e-07], shape=(4,), dtype=float32)
0
[ 14.049104    -2.825729   -23.468729    -0.17663112]
1
tf.Tensor([1.0000000e+00 1.7108880e-18 5.9606886e-24 3.0932619e-16], shape=(4,), dtype=float32)
0
[ 26.271742 -14.637776 -27.205114  -9.440395]
2
tf.Tensor([1.0000000e+00 2.8109572e-12 5.3797483e-12 5.3799031e-08], shape=(4,), dtype=float32)
0
[ 13.626369  -12.971127  -12.32201    -3.1116416]
3
tf.Tensor([1.0000000e+00 1.4500418e-17 1.3242957e-21 1.4188171e-14], shape=(4,), dtype=float32)
0
[ 23.953075  -14.819278  -24.12033    -7.9332924]
4
tf.Tensor([1.0000000e+00 1.7815533e-12 1.5819272e-17 3.1454103e-08], shape=(4,), dtype=float32)
0
[ 16.929901   -10.123633   -21.7554      -0.34483594]
5
tf.Tensor([1.0000000e+00 3.1441668e-13 1.6209780e-20 5.2070327e-13], shape=(4,), dtype=float32)
0
[ 21.1

In [20]:
External_data=pd.read_csv('/content/drive/MyDrive/NeuralNetwork/Dokt/Etap2/TestExternalNoHeaderPo100.csv', sep=',',header=None)
#data =External_data.values[1]
# print(data)
# classes = model.predict(data.reshape(1,100), batch_size=1)
# #print(model.predict(test_data.reshape(1,99), batch_size=1))
# pred = np.argmax(classes) #wskazanie do ktorej klasy została przporzadkowana dana testowa
# print(pred)  
# print(classes) 

#np.genfromtxt('myfile.csv',delimiter=',')
good_adjustable = 0
good_shape = 0
good_traingle = 0
good_wrench = 0
wrong_adjustable = 0
wrong_shape = 0
wrong_traingle = 0
wrong_wrench = 0
wrong_adjustable_table = []
wrong_shape_table = []
wrong_traingle_table = []
wrong_wrench_table = []
wrong_adjustable_table_sample = []
wrong_shape_table_sample = []
wrong_traingle_table_sample = []
wrong_wrench_table_sample = []
first_data_of_adjustable = 0
last_data_of_adjustable = 99
first_data_of_shape = 100
last_data_of_shape = 199
first_data_of_traingle = 200
last_data_of_traingle = 299
first_data_of_wrench = 300
last_data_of_wrench = 399
sum_of_possibilitie_for_adjustable = 0
sum_of_possibilitie_for_shape = 0
sum_of_possibilitie_for_traingle = 0
sum_of_possibilitie_for_wrench = 0
sum_all = 0
prediction =0
print("Test danych zewnętrznych. Jest po 100 danych z każdej klasy")
print("Klasyfikacja obiektów {'adjustable': 0, 'shape': 1, 'triangle': 2, 'wrench': 3}")
for th in range(400):
  print(th) 
  data =External_data.values[th]
  classes = model.predict(data.reshape(1,100), batch_size=1)
  prediction =classes[0,0]
  print(prediction)
  # print(round(prediction,0))
  if (th>=first_data_of_adjustable and th<=last_data_of_adjustable): # 99 bo zaczyna od 0
    sum_of_possibilitie_for_adjustable = sum_of_possibilitie_for_adjustable + prediction
    if (round(float(prediction)) == 0):
      good_adjustable=good_adjustable+1
    else:
      wrong_adjustable_table_sample.append(th)
      wrong_adjustable_table.append(prediction)
      wrong_adjustable=wrong_adjustable+1
  elif (th>=first_data_of_shape and th<=last_data_of_shape):
    sum_of_possibilitie_for_shape = sum_of_possibilitie_for_shape + prediction
    if (round(float(prediction)) == 1):
      good_shape=good_shape+1
    else:
      wrong_shape_table_sample.append(th)
      wrong_shape_table.append(prediction)
      wrong_shape=wrong_shape+1    
  elif (th>=first_data_of_traingle and th<=last_data_of_traingle):
    sum_of_possibilitie_for_traingle = sum_of_possibilitie_for_traingle + prediction
    if (round(float(prediction)) == 2):
      good_traingle=good_traingle+1
    else:
      wrong_traingle_table_sample.append(th)
      wrong_traingle_table.append(prediction)
      wrong_traingle=wrong_traingle+1  
  elif (th>=first_data_of_wrench and th<=last_data_of_wrench):
    sum_of_possibilitie_for_wrench = sum_of_possibilitie_for_wrench + prediction
    if (round(float(prediction)) == 3):
      good_wrench=good_wrench+1
    else:
      wrong_wrench_table_sample.append(th)
      wrong_wrench_table.append(prediction)
      wrong_wrench=wrong_wrench+1  




  # pred = np.argmax(classes) #wskazanie do ktorej klasy została przporzadkowana dana testowa

  # print(th) 
  # print(classes) 
  # print(max(classes))
  # print(round((classes[1])))
  # if (th>=first_data_of_adjustable and th<=last_data_of_adjustable): # 99 bo zaczyna od 0
  #   sum_of_possibilitie_for_adjustable = sum_of_possibilitie_for_adjustable + (float(classes)/100)
  #   if (round(float(classes)) == 0):
  #     good_adjustable=good_adjustable+1
  #   else:
  #     wrong_adjustable_table.append(classes)
  #     wrong_adjustable=wrong_adjustable+1
  # elif (th>=first_data_of_shape and th<=last_data_of_shape):
  #   sum_of_possibilitie_for_shape = sum_of_possibilitie_for_shape + (float(classes)/100)
  #   if (round(float(classes)) == 1):
  #     good_shape=good_shape+1
  #   else:
  #     wrong_shape_table.append(classes)
  #     wrong_shape=wrong_shape+1    
  # elif (th>=first_data_of_traingle and th<=last_data_of_traingle):
  #   sum_of_possibilitie_for_traingle = sum_of_possibilitie_for_traingle + (float(classes)/100)
  #   if (round(float(classes)) == 2):
  #     good_traingle=good_traingle+1
  #   else:
  #     wrong_traingle_table.append(classes)
  #     wrong_traingle=wrong_traingle+1  
  # elif (th>=first_data_of_wrench and th<=last_data_of_wrench):
  #   sum_of_possibilitie_for_wrench = sum_of_possibilitie_for_wrench + (float(classes)/100)
  #   if (round(float(classes)) == 3):
  #     good_wrench=good_wrench+1
  #   else:
  #     wrong_wrench_table.append(classes)
  #     wrong_wrench=wrong_wrench+1  


sum_all = good_adjustable+wrong_adjustable+good_shape+wrong_shape+good_traingle+wrong_traingle+good_wrench+wrong_wrench
  #print(round(classes,12))
  #print(round(float(classes))) - zaokraglenie powoduje przyporzadkowanie do klasy
print("--------Well Classified-------------------") 
print("----Adjustable----")
print("good adjustable = "+str(good_adjustable))
print("Wrong adjustable = "+str(wrong_adjustable))
print("Wrong adjustable test ")
print(wrong_adjustable_table_sample)
print(wrong_adjustable_table)
print("Average value of possibilities " + str(sum_of_possibilitie_for_adjustable/100) )
print("----Shape----")
print("good shape = "+str(good_shape))
print("Wrong shape = "+str(wrong_shape)) 
print("Wrong shape test:")
print(wrong_shape_table_sample)
print(wrong_shape_table)
print("Average value of possibilities " + str(sum_of_possibilitie_for_shape/100) )
print("----Triangle----")
print("good triangle = "+str(good_traingle)) 
print("Wrong triangle = "+str(wrong_traingle))
print("Wrong triangle test")
print(wrong_traingle_table_sample)
print(wrong_traingle_table)
print("Average value of possibilities " + str(sum_of_possibilitie_for_traingle/100))
print("----Wrench----")
print("good wrench = "+str(good_wrench))       
print("Wrong wrench = "+str(wrong_wrench))
print("Wrong wrench test:")
print(wrong_wrench_table_sample)
print(wrong_wrench_table)
print("Average value of possibilities " + str(sum_of_possibilitie_for_wrench/100) )
print("----Sum Up----")
print("All Tests ="+str(sum_all))
%load_ext autotime

Test danych zewnętrznych. Jest po 100 danych z każdej klasy
Klasyfikacja obiektów {'adjustable': 0, 'shape': 1, 'triangle': 2, 'wrench': 3}
0
14.049104
1
26.271742
2
13.626369
3
23.953075
4
16.929901
5
21.129929
6
17.493998
7
20.954195
8
18.180977
9
20.75151
10
17.403965
11
20.2485
12
32.493275
13
21.886255
14
5.27825
15
19.407602
16
17.54522
17
19.17944
18
16.04914
19
18.945997
20
14.694256
21
18.254906
22
15.668797
23
17.827679
24
14.851075
25
18.140339
26
15.428769
27
19.013165
28
16.660187
29
18.488134
30
29.094208
31
23.270561
32
10.459051
33
23.171183
34
29.02215
35
21.738792
36
12.216636
37
22.299824
38
11.797753
39
16.852095
40
12.156007
41
19.83848
42
13.054746
43
24.161837
44
32.591515
45
19.935778
46
14.269756
47
26.52069
48
32.517544
49
20.818575
50
16.697021
51
26.465271
52
33.1404
53
21.726288
54
33.487175
55
22.564648
56
35.183537
57
21.115807
58
8.6299
59
26.219454
60
31.191925
61
18.35528
62
33.85844
63
19.730362
64
30.357141
65
18.555412
66
31.674301
67
17.919903
68
3

In [ ]:
#testowanie
test_data = np.array([-1.3162,-0.0819,-0.0058,-0.0006,-0.0001,-0.0000,-0.0000,0.0000,0.0000,0.0000,0.0001,0.0003,0.0019,0.0320,0.0488,0.0656,0.0596,0.0340,-0.0140,-0.0023,-0.0366,-0.0303,-0.0273,-0.1521,-1.2484,-1.1544,-0.6533,-0.1641,0.2247,0.2720,0.2933,0.1415,-0.0826,-0.1195,0.0805,0.5166,0.7484,0.7484,0.7484,0.7484,0.7484,0.7484,0.7484,0.7484,0.7484,0.7484,0.7484,0.7484,0.7484,0.7484,0.5098,0.0626,-0.2008,-0.0070,0.2676,0.2962,0.0732,-0.1376,-0.1235,0.0550,-0.0299,-0.3594,-0.4464,-0.5023,-0.3306,-0.4530,-0.5977,-0.6141,-0.6141,-0.6141,-0.6141,-0.6141,-0.6141,-0.6141,-0.6141,-0.5524,-0.1471,-0.0957,0.0121,0.0147,0.0303,0.0305,0.0344,0.0658,0.0765,0.0039,0.0004,0.0000,0.0000,0.0000,0.0000,-0.0000,-0.0000,-0.0000,-0.0001,-0.0006,-0.0036,-0.0209,-0.1863,-1.3374])
classes = model.predict(test_data.reshape(1,100), batch_size=1)
#print(model.predict(test_data.reshape(1,99), batch_size=1))
pred = np.argmax(classes) #wskazanie do ktorej klasy została przporzadkowana dana testowa
print(pred)  
print(classes) 

0
[[2.9148798]]


In [ ]:
#save model w formacie h5
model.save('housing_model.h5')

In [ ]:
#scaigniecie old model
old_model = keras.models.load_model('housing_model.h5')